title: msvice.com docs
description: Documentation for the msvice.com demo site
author: "Klaus Harrer-Nemecek"

theme: minima

# Minima social links
#github_username: itadmin-msvice
linkedin_username: klausharrernemecek
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

markdown: kramdown
